services:
  rdesktop-xfce:
    build:
      context: .
      tags:
        - "ghcr.io/gnzsnz/rdesktop-xfce:latest"
    image: ghcr.io/gnzsnz/rdesktop-xfce:latest
    container_name: rdesktop-xfce
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RDP_USER=abc
      # - RDP_PASSWORD=changeme
    volumes:
      - ./config:/config
      # custom init scripts / services, inherited from linuxserver/baseimage-ubuntu
      # uncomment if firefox fails
      # - ./custom-cont-init.d:/custom-cont-init.d
      # - ./custom-services.d:/custom-services.d
      # uncomment if firefox fails
      # - firefox-profile:/config/.config/mozilla/firefox
    ports:
      - "3389:3389"
    shm_size: "1gb"
    restart: unless-stopped

# uncomment if firefox fails
# volumes:
#   firefox-profile:
